version: 2

jobs:
  build:
    branches:
      only:
        - dev
        - master
        - ci
    docker:
      - image: "debian:sid"
    steps:
      - checkout
      - run:
          name: Updating
          command: apt-get update
      - run:
          name: Installing git, gcc, g++, boost, cmake, openssl
          command: apt-get install -y git gcc g++ libboost-all-dev cmake openssl libssl-dev
      - run:
          name: Fetch submodules
          command: git submodule update --init --recursive
      - run:
          name: Building
          command: cmake -H. -Bbuild && cmake --build build
      - run:
          name: Testing
          command: (cd build; ctest)
      - run:
          name: Run
          command: ./bin/moros -v
